version: '3.8'
services:
  app:
    container_name: go-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_CONNECTION_STRING: "postgres://postgres:postgres@db:5432/postgres"
  db:
    container_name: postgres-db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
