version: '3.8'
services:
  app:
    container_name: go-app
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION_STRING: "postgres://postgres:postgres@db:5432/postgres"
    depends_on:
      - db
  db:
    container_name: postgres-db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test:
    container_name: go-app-test
    build: .
    depends_on:
      - db
    env_file:
      - tests/.env
    command: go test ./...
    volumes:
      - .:/app


volumes:
  postgres_data:
